backend:
  name: github
  branch: main
  repo: BrigadaSOS/BrigadaSOS-docs

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
display_url: https://brigadasos.xyz
site_url: https://brigadasos.xyz
logo_url: https://brigadasos.xyz/img/logo.png

slug:
  sanitize_replacement: "/"

collections:
- name: docs
  label: "Inicio"
  folder: docs
  identifier_field: title
  extension: mdx
  format: frontmatter
  create: true
  widget: "list"
  preview_path: "/"

  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: guia-principal
  label: "Guía Prinicpal"
  folder: docs/guia-principal
  identifier_field: title
  extension: mdx
  format: frontmatter
  create: true
  widget: "list"
  preview_path: "guia-principal/{{fields.slug}}"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: configuracion
  label: "Configuración"
  folder: docs/configuracion
  identifier_field: title
  extension: mdx
  format: frontmatter
  create: true
  widget: "list"
  preview_path: "configuracion/{{fields.slug}}"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: otras-guias
  label: "Otras guías"
  folder: docs/otras-guias
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  preview_path: "otras-guias/{{fields.slug}}"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: utilidad
  label: "Utilidad"
  folder: docs/utilidad
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  preview_path: "utilidad/{{fields.slug}}"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: miscelasneo
  label: "Miscelasneo"
  folder: docs/miscelasneo
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  preview_path: "miscelasneo/{{fields.slug}}"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown