backend:
  name: github
  branch: main
  repo: BrigadaSOS/BrigadaSOS-docs

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow

collections:
- name: docs
  label: "Inicio"
  folder: docs
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: principal-guide
  label: "Guía Prinicpal"
  folder: docs/principal-guide
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: configuration
  label: "Configuración"
  folder: docs/configuration
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: various-guide
  label: "Otras guías"
  folder: docs/various-guide
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: utility
  label: "Utilidad"
  folder: docs/utility
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown
- name: misc
  label: "Misc"
  folder: docs/misc
  identifier_field: title
  extension: md
  format: frontmatter
  create: true
  widget: "list"
  fields:
    - label: Título
      name: title
      widget: string
    - label: URL 
      name: slug
      widget: string
    - label: Position en el sidebar
      name: sidebar_position
      widget: number
      min: 1
    - label: Contenido
      name: body
      widget: markdown